// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolAppEntities;

[Table("Administration", Schema = "Admin")]
public partial class Administration
{
    [Key]
    public int AdminId { get; set; }

    [StringLength(250)]
    public string Username { get; set; }

    [StringLength(50)]
    public string PasswardHash { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string FullName { get; set; }

    [StringLength(50)]
    public string Phone { get; set; }

    [StringLength(50)]
    public string Email { get; set; }

    [StringLength(250)]
    public string Address { get; set; }

    public bool? Status { get; set; }

    public bool? IsDeleted { get; set; }
}