// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolAppEntities;

[Table("Classes", Schema = "Admin")]
public partial class Class
{
    [Key]
    public int ClassId { get; set; }

    [Required]
    [StringLength(250)]
    public string ClassName { get; set; }

    public int ClassStrength { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    public bool Status { get; set; }

    public int TeacherId { get; set; }

    public bool IsDeleted { get; set; }
}