// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolAppEntities;

[Table("FeeStructures", Schema = "Finance")]
public partial class FeeStructure
{
    [Key]
    public int FeeStructureId { get; set; }

    public int ClassId { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal? AdmissionFee { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal TutionFee { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal? TransportFee { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal? OtherFee { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal? LabFee { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal Fine { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal TotalFee { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DueDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AfterDueDate { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal? DueDateFee { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal? AfterDueDateFee { get; set; }

    public bool IsDeleted { get; set; }
}