// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolAppEntities;

[Table("Genders", Schema = "Setup")]
public partial class Gender
{
    [Key]
    public int GenderId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string GenderName { get; set; }

    public bool IsDeleted { get; set; }
}