// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolAppEntities;

[Table("Students", Schema = "Setup")]
public partial class Student
{
    [Key]
    public int StudentId { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string StudentName { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string FatherName { get; set; }

    [Required]
    [StringLength(50)]
    public string FatherContact { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string GaurdianName { get; set; }

    [Required]
    [StringLength(50)]
    public string GaurdianContact { get; set; }

    [Required]
    [StringLength(500)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    [StringLength(250)]
    public string Email { get; set; }

    [Required]
    public string StudentPictureUrl { get; set; }

    public DateOnly StudentDOB { get; set; }

    [StringLength(50)]
    public string FatherIdCardNum { get; set; }

    [StringLength(50)]
    public string StundentIdCardNum { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EnrollmentDate { get; set; }

    public int GenderId { get; set; }

    public int ClassId { get; set; }

    public bool IsDeleted { get; set; }
}