// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolAppEntities;

[Table("Teachers", Schema = "Setup")]
public partial class Teacher
{
    [Key]
    public int TeacherId { get; set; }

    [Required]
    [StringLength(250)]
    public string TeacherName { get; set; }

    [Required]
    [StringLength(500)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    [Required]
    [StringLength(50)]
    public string Qualification { get; set; }

    [StringLength(250)]
    public string Specialization { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime HiringDate { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal Salary { get; set; }

    public int GenderId { get; set; }

    public int DepartmentId { get; set; }

    public bool Status { get; set; }

    public bool IsDeleted { get; set; }
}